### PR TITLE
Indonesian Translations for Snap!

### PR DESCRIPTION
**Pull request by DrKat123**
I've been working on this for 2 days and now it's finally finished :smile:
If anything is wrong in the translations or the file itself i will fix it as soon as possible

### CODE REVIEW

**Comment by jmoenig** [comment]
Yay!!! Wow!!! This is AWESOME! Thank you so much!

... and it's *just in time*, too, to be pulled for the upcoming release, following later today. Fantastic. It's so great that kids in Indonesia will now be able to play with Snap, too!! Thank you, thank you, thank you!!

**Comment by DrKat123** [comment]
Your welcome :)

**Comment by DrKat123** [comment]
added some updates I forgot to add

**Comment by liam4** [comment]
:tada: Yay, more translations!

@Rumanti, you're Indonesian, I think..? Perhaps you could quickly skim through the translation to make sure everything's right? <sub>(Just because it's always a good idea to check these kinds of things.)</sub>

**Comment by DrKat123** [comment]
Yeah :stuck_out_tongue:

There _will_ be some grammar mistakes though because i haven't checked all of them

**Comment by Rumanti** [comment]
@liam4 I just checked out GH today... But here.

1) line 243, menghadap (typo)
2) line 251, situs (untranslated)
3) line 252, sebuah (grammar)
4) line 254, suatu, not sebuah; komputermu, not komputer mu; berkasnya, not file nya (grammar)
5) line 294, gerak OR pindah, not maju (context)
6) line 296 + 298, derajat, not derajad (typo)
7) line 318, pinggir not ujung (context)
8) line 334 + 338, detik, not dtk (OPINION-BASED)
9) line 350, grafis, not grafik (context)
10) line 381, istirahat (typo)
11) line 385, sebesar, not sebanyak (context..?)
12) line 419 + 421 + 435, ketika not Ketika (caps)
13) line 511, siapa not Siapa (caps)
14) line 634, Buat, not buat (caps)

Also, the translation for _block_ is inconsistent.

**Comment by DrKat123** [comment]
Yeah, I should fix that

**Comment by Rumanti** [comment]
Also, the translation for _block_... Which would you stick with? Block, blok, or balok? Personally, I prefer balok. It is correct grammatically etc. And it's a legit word.

**Pull request merged**
