### PR TITLE
Checking if user is verified on session init

### PR DESCRIPTION
**Pull request by bromagosa**
This makes sure we're checking if a user is verified when the session starts (so, when you open Snap!).

We're also adding some info on how to get your verification code.

Please let me know if the wording is okay.

### CODE REVIEW

**Comment by brianharvey** [comment]
Looks fine to me.  Thanks.

**Comment by jmoenig** [comment]
Is this an emergency patch? Do you want me to pull it now, make a minor release and put it online right away, or should we collect what else is coming up for a maintenance release next week or so? (Either way is fine with me)

**Comment by jmoenig** [comment]
WAIT! Now it's sending me a message that my account is still unverified and asks me to click on a link from an email I never got. SOMETHING is VERY wrong here, I think I understand all the hubbub that's going on. Can we talk about this real quick in person?

**Comment by jmoenig** [comment]
Oh, now I'm confused. I need to log out and log in again, and now I'm no longer getting the message. Hmm.... so everything seems to be right, except when users chose to stay logged in.

**Comment by bromagosa** [comment]
No, don't worry, that happens because the SnapCloud object didn't have the
verified field when you accessed Snap!. Once you log in again, it will get
it from the server.

I couldn't think of a clean way to prevent this from happening to users who
were already logged in. We can revert this until we find a solution if you
think it's important.

2018-02-20 16:48 GMT+01:00 Jens Mönig <notifications@github.com>:

**Comment by brianharvey** [comment]
I just tried connecting; I wasn't logged in before.  When I clicked login, 
I got the dialog.  As soon as I typed my login, before I had a chance to 
type my password, I got the account-unverified message covering the login 
dialog.  This is very disconcerting!  At least it should wait until I enter 
my password.

And, I'm a user who stays always logged in, so I want that to work.  :-)

**Comment by bromagosa** [comment]
@brianharvey is this still happening to you? I just tried it at the Citilab with several accounts and nobody had this issue.

**Comment by brianharvey** [comment]
Worked this time.  But I'm assuming it's just once per user, no?

**Comment by brianharvey** [comment]
... but "stay logged in" isn't working.  I have to re-log in every time.

**Comment by bromagosa** [comment]
See my email, please :)

2018-02-20 19:38 GMT+01:00 Brian Harvey <notifications@github.com>:

**Pull request merged**
