### PR TITLE
Switch media list files to JSON

### PR DESCRIPTION
**Pull request by BookOwl**
I have converted the media list files to JSON as requested in issue #1594 by @cycomachead. This greatly simplifies `IDE_Morph.prototype.parseResourceFile`, while at the same time making it more robust and probably faster.

### CODE REVIEW

**Comment by cycomachead** [comment]
Why make these be under `resources`?

It seems better to simply have each file contain an array. 

Also, I wasn't sure whether it was best to duplicate the keys every time or just store items as arrays.

**Comment by BookOwl** [comment]
For some reason I thought that arrays weren't allowed to be the top level thing in JSON, I'll change it.

**Comment by BookOwl** [comment]
@jmoenig?

**Comment by jmoenig** [comment]
I don't have any strong opinions about this. @cycomachead ? @brianharvey ?

Oh, wait, maybe I do, sorta.

I don't think @cycomachead's little parsing function for his current format is too complicated at all, it's basically very straightforward and just a very few lines of code. OTOH I don't much mind JSON, either. The part I don't like so much about JSON is that it requires the name of each field in every instance of that field. That way data files become exponentially bigger the more data they hold. JSON is cool for heterogeneous data, but for a table structure in which every record has the exact same structure I've never understood why people love JSON. Also, all this syntax in the data file increases the risk for bugs. I guess people love JSON because ... they love JSON, not because there's an actual benefit in the case of a table.

Is that too harsh?

**Comment by brianharvey** [comment]
No strong opinions.  Michael's #1594 argues for this on robustness grounds.  Whatever.

**Comment by cycomachead** [comment]
For the JSON structure, we don't need to duplicate the property names. 

We can use do:
```json
[ 
    [ 'fileName', 'title', 'description'],
    ...
]
```
And then map over arrays to add properties. And we can even make the  `description` optional for fields that don't have one.

Either way, I still support JSON because there's been a number of times that LIBRARIES has been edited to have spaces instead of tabs delimiting something.

**Comment by jmoenig** [comment]
this is superseded by Eric Hakenholz's other pull request, so we'll close this one. Thanks!

**Pull request closed without merging**
