### PR TITLE
New update of the Spanish language file

### PR DESCRIPTION
**Pull request by cienciascontic**
I've added new translations to the lang-es.js. See attached here the file in zip format. Sorry I'm not so experienced in GitHub!!
[lang-es.js.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/1356041/lang-es.js.zip)

### CODE REVIEW

**Comment by jmoenig** [comment]
Umm, are you sure you want to merge this into the main Snap trunk? It looks like this might go into the Monash version...

**Comment by jguille2** [comment]
Hi @jmoenig ,

It's clear this PR is not for Snap! In any case, I've seen the zip attached by @cienciascontic and it has the _lang-es.js_ updated... and it seems fine.
I think you can update this file.

Joan

**Comment by cienciascontic** [comment]
Yes!! This should go into the monash version. Sorry!!

El 6 oct. 2017 3:56 AM, "Jens Mönig" <notifications@github.com> escribió:

Umm, are you sure you want to merge this into the main Snap trunk? It looks
like this might go into the Monash version...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/1881#issuecomment-334674287>,
or mute the thread

**Comment by jguille2** [comment]
Hi @jmoenig and @cienciascontic,

Yes, as I said this PR is not mergeable... but I point again that the zip file attached (not the PR) into the first commit is fine and adds a lot of strings to Spanish translation.

Then, we can update Spanish translation with Cristián work. If you agree, I'll add (and check) this changes in another PR.

Anyway, this PR must be closed.

**Comment by jmoenig** [comment]
Hi @jguille2 , it would be wonderful if you could help with this. Thank you!

**Comment by bromagosa** [comment]
Closing as alredy merged in #1992

**Pull request closed without merging**
