### PR TITLE
Working for #2132 Tools into Catalan, Spanish and French

### PR DESCRIPTION
**Pull request by jguille2**
- 1 fix and 3 additions to French language.
- Tools blocks translated into Catalan, Spanish and French.
French translations by @nathalierun. Thanks!

### CODE REVIEW

**Comment by jmoenig** [comment]
Yay! thank you, @jguille2 and @nathalierun! I'll pull this asap for the next minor release (probably in a week or so).

**Comment by nathalierun** [comment]
Please @jmoenig, wait for a new pull request by @jguille2 because I made some misunderstandings. We are thinking about them.

**Comment by jmoenig** [comment]
Okay, @nathalierun , no worries! I won't make a new release before the end of next week anyway. Hey, it's great that we're going to have updated translations including the tools!!

**Comment by jguille2** [comment]
Hi @jmoenig,
After some discussion on #2132 (just closed now), I've comitted two changes and I think this is ready to merge :smile:

**Comment by jmoenig** [comment]
Yay, thank you so much, @jguille2 and @nathalierun ! I'm looking forward to merging this into a new minor release later this week (probably^^)

**Pull request merged**
