### PR TITLE
Piano Keyboard, Replaces #852

### PR DESCRIPTION
**Pull request by cycomachead**
Same code as #852, but fixes the merge.

### CODE REVIEW

**Comment by cycomachead** [comment]
Bump. :-)

**Comment by jmoenig** [comment]
This is nice, thank you! No need to "bump" this PR, though. I'll look through all the open PRs as I'll be preparing the next release anyway. But that may take a while, perhaps even until after Christmas. Currently I'm working hard on preparing Snap to work better on larger data sets.

**Comment by jmoenig** [comment]
Wait! I *did* forget about this after all, shame!! Putting it up on my list to review....

**Comment by jmoenig** [comment]
We want to get this into the release. Blessing and adding "under review", so we don't forget about it (again) :-)

**Comment by bromagosa** [comment]
Merged into 'dev' branch in cf29bec85beeec0100cc095d0e02c4899537c7f9, and reviewed in 033584d948c942b1fc1fc20b2dd9610c25050b49.

**Pull request closed without merging**
