### PR TITLE
Refactored symbolCanvasColored. Fixes #1139

### LINKED ISSUE #1139: Suggested symbolCanvasColored Refactor
Currently, it is difficult to add a new symbol to the SymbolMorph (in `symbolCanvasColored`). The large switch case makes extending it a little tricky (ideally, you would subclass SymbolMorph and override this method - with a `super` call of course). Of course, you can also override the entire function with a slightly modified version but that is ugly and will not allow you to receive any new symbols, etc from the core Snap! project. This approach also requires that `SymbolMorph.prototype.names` is modified to also contain the new symbol.

It would be nice if this functionality was stored in a dictionary like SymbolMorph.SYMBOLS which would allow the easy addition of new symbols by simply adding the entry and then writing the associated function (no method override/subclassing or updating `SymbolMorph.prototype.names`)

### PR DESCRIPTION
**Pull request by brollb**
This is a suggested refactor for issue #1139

### CODE REVIEW

**Comment by cycomachead** [comment]
You might find #1109 interesting. :) I personally :+1: this change, but I'm not Jens!

**Comment by jmoenig** [comment]
Yes, this looks reasonable to me.
As an alternative I've been thinking about ever since introducing SymbolMorph we could get rid of the the whole symbol-drawing method binding and simply follow the convention that the drawing method's name always follows the conventions:

```JavaScript
'drawSymbol' + sym[0].toUpperCase() + sym.slice(1)
```

This would be even less code while being way more flexible...
What do you think?

**Comment by cycomachead** [comment]
I'd personally like to see
```js
'drawSymbol' + sym[0].toUpperCase() + sym.slice(1)
```
as
```js
'drawSymbol' + capitalize(sym)
```
Where `capitalize` is defined anywhere convenient.

**Comment by brollb** [comment]
I like the idea of enforcing the naming convention. The only drawback to this approach is it makes the enumerating the supported symbols difficult (as done in [byob.js](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/1140/files#diff-afb7a00b1866ca6d6477b267bc8c644cL2456))

**Comment by jmoenig** [comment]
Enumeration of available symbols is a good point, @brollb

**Pull request closed without merging**
