### PR TITLE
Fixes #709

### LINKED ISSUE #709: Add Events category
The Control category is getting crowded.
I recommend you to add all new Scratch 2.0 blocks, except the ones you've already added.
Add a More Blocks category and change the default colour of new blocks to purple.
Add also an Events category with all When hats, Message reporter and Broadcast blocks

### PR DESCRIPTION
**Pull request by luis140219**
This pull request fixes #709 and #705.
See the result: http://luis140219.github.io/Snap--Build-Your-Own-Blocks/snap.html

### CODE REVIEW

**Comment by Gubolin** [comment]
Well... do we really need another category? And yet another, empty one ("obsolete")?
Also, you should test your changes. There are no blocks in the "Events" category as you just changed the color (-> look down in the source code of `objects.js` and `blocks.push` the blocks into the right category).

**Comment by jmoenig** [comment]
This is probably not going to happen for the impending release. I really don't want to introduce more categories.

**Comment by luis140219** [comment]
I've removed "obsolete" from the visible category list in commit luis140219/Snap--Build-Your-Own-Blocks@e18a9bdd7571.

**Comment by luis140219** [comment]
I forgot to put the versions of blocks.js, objects.js and gui.js at 2015-March-13.

**Pull request closed without merging**
