### PR TITLE
Support Loading More Resources from the `resourceURL` method

### PR DESCRIPTION
**Pull request by cycomachead**
These are a few places which load resources, that might also be in subfolders. I ran into these for autograding and for the desktop app.

### CODE REVIEW

**Comment by jmoenig** [comment]
Hmm... These resources are the tools file, translations and the logo. I think these are special and should actually be always present and loaded from their absolute locations, especially the translations and the logo, don't you agree?

**Comment by cycomachead** [comment]
For s.b.e this doesn't change anything. 

For other apps, the issue is that the current method doesn't account for the case if you need to serve Snap! from a dynamic server. That's what's being done for autograding, and for the snap desktop app too. So in those case the override for `resourceURL` looks a bit different, but still relatively simple. (For autograding and the desktop all that's needed is to preprend some stuff to the URL, but that has to happen for the tools xml and all files, not just the content in subfolders.)

**Comment by jmoenig** [comment]
My concern is that I want translations to also work when I simply download the sources and open snap locally on my computer without setting up a local web server. It looks like this should still work. Have you tried that? I really need that to test all the translations, and it's a big feature because there are very many people using Snap that way.

**Comment by cycomachead** [comment]
Yeah, that all works fine. 

Essentially, in normal Snap<em>!</em> `resourceURL` is basicaly a no-op. (Well, if you're passing in folders, it will add the `/` for you, but otherwise, it's a pretty simple function.)

**Comment by jmoenig** [comment]
Okay, then I'm pulling it now. Thanks!
Any other last minute PRs coming in, or any really pressing things that should go into the upcoming release?

**Comment by cycomachead** [comment]
Not super pressing, I suppose, but #1084 is done from my end, I think, and would be helpful.

**Pull request merged**
