### PR TITLE
fix a bug 

### PR DESCRIPTION
**Pull request by SmallBookworm**
The first character can be selected now.

### CODE REVIEW

**Comment by SmallBookworm** [comment]
And I add a other pull request...only the last commit is necessary.Sorry, @DarDoro

**Comment by jmoenig** [comment]
Is this still current, or has it been superseded by @bromagosa 's recent text-editing efforts?

**Comment by bromagosa** [comment]
This is fixed already, it can be closed :)

**Comment by jmoenig** [comment]
Thanks, Bernat!

**Pull request closed without merging**
