### PR TITLE
media import dialog with thumbnails

### PR DESCRIPTION
**Pull request by ubertao**
This PR changes import costumes/backgrounds menu to dialog boxes with thumbnails of media, making import process more intuitive/fun.

Given the limited size of current media library, pagination was not implemented, this is something should be improved in the future.

Screenshots:
import
import-bg

### CODE REVIEW

**Comment by jmoenig** [comment]
Oh wow. This is really beautiful! Thank you, I'll pull this later today and integrate it right away!!

**Comment by liam4** [comment]
This looks great! Will it cause an issue on devices with access to bad internet, though? If the preview image loading is synchronous, it may take these devices a long time to open up the media library.

**Comment by ubertao** [comment]
Once the library file is read, the dialog will open right away with place holder images (currently the turtle icon, sorry I couldn't find a more proper resource for loading status), then thumbnails will be loaded in background.

**Comment by cycomachead** [comment]
This is really awesome! 👍 

My only quibble is that the background color of the dialog looks off.

I'll add an issue about pagination later. Now that graphics are done, it'd be great to implement the same thing as a preview for the sounds dialog, where you get a grid of play buttons.

**Comment by jmoenig** [comment]
Don't worry, @cycomachead , I've already fixed that, and I'm also working on a few other small issues...

**Comment by jmoenig** [comment]
Thanks again, @ubertao ! I've tweaked your contribution somewhat, mostly making the dialog box resizable, the icons double-clickable and avoiding some causes of minor JS errors: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/711b9a431fa34fbfc49669ff2255b52ca201b5a5
But the original contribution and the design of it is still very much yours. I hope you don't mind, this is great, I really appreciate it!

**Comment by ubertao** [comment]
Great, this is definitely better!

**Pull request merged**
