### PR TITLE
Control / ⌘ key + arrow key lets us navigate through words now.

### PR DESCRIPTION
**Pull request by bromagosa**

### CODE REVIEW

**Comment by jmoenig** [comment]
Thanks, Bernat! I'll pull it with the next batch of changes.

**Comment by show0k** [comment]
In OSX, it is not the command key which is usually used to navigate throw words, but the alt key !

**Comment by bromagosa** [comment]
Thanks @show0k, I've updated the pull request accordingly...

**Comment by jmoenig** [comment]
Hi, Théo - @show0k - Wow, I didn't even realize the text navigation shortcuts on a Mac, but I still remember the ones I used on Windows for many years :-)

So, the alt-key navigates among words, and the cmd-key goes to the beginning or end of line, right?

**Comment by show0k** [comment]
`So, the alt-key navigates among words, and the cmd-key goes to the beginning or end of line, right?`
Exactly !

**Comment by liam4** [comment]
On the topic of these navigation controls, ctrl-A goes to the beginning of the line (or paragraph, depending on the environment), and ctrl-E goes to the end.

**Pull request closed without merging**
