### PR TITLE
Fixes in the Indonesian translation file

### PR DESCRIPTION
**Pull request by DrKat123**

### CODE REVIEW

**Comment by liam4** [comment]
More specifically, fixes in the Indonesian translation.

**Comment by DrKat123** [comment]
Okay :P

**Comment by jmoenig** [comment]
You sure about this change? I don't know Indonesian, but "Karakter" sounds more like an adaptation of the workd "character" to me, whereas nobody really knows what a "sprite" is. Which word do you think kids in Indonesia will understand better?

**Comment by DrKat123** [comment]
I can't seem to find an even better word for a "sprite." "Karakter" might sound a bit better, but i'm not quite sure

"Sprite" might be confused with the fizzy drink from The Coca-Cola company, [https://en.wikipedia.org/wiki/Sprite_(soft_drink)](Sprite) (it's really popular here)

**Comment by brianharvey** [comment]
How about "actor" or "agent" (not in the real-estate-agent sense, but someone-who-takes-action)?

**Comment by DrKat123** [comment]
0kay

_s0rry ab0ut that, my andr0id's t0uchscreen is br0ken_

**Comment by brianharvey** [comment]
Okay, as in "yes I'll revise the pull request by translating "actor" or "agent" into Indonesian," or okay as in "I'm done thinking about this"?

**Comment by DrKat123** [comment]
I _might_ stick with "karakter" f0r n0w

**Comment by liam4** [comment]
Quoting Oxitro responding to me [on Rumanti's profile](https://scratch.mit.edu/users/Rumanti/#comments-23364227):

> Hi Liam! I am Rumanti's friend, who is also quite interested to Snap! For me you can use the Indonesian word "karakter" for the context. I'm Indonesian by the way.

So more input there.

**Comment by DrKat123** [comment]
So I'll just close this pr

**Pull request closed without merging**
