### PR TITLE
Fix Issues for Exporting Files

### LINKED ISSUE #1825: Export variable fails in dev 4.1 in Chrome
http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=lhs-dmahalko&ProjectName=Hexadecimal%20string%20to%20binary%20v0.1

Run this project and try to export the variable watcher on the stage.  Works for me in Firefox, and in non-dev in Chrome, but dev in Chrome makes a new window that (for the user who reported it) is empty, and for me just flashes in and out of existence.  (Nothing in JS console.)

### PR DESCRIPTION
**Pull request by cycomachead**
Fixes #1825, related to #1827 

This current disables anything from being exported in a new window. If we choose to implement the work around in #1827, then we should do that separately.

### CODE REVIEW

**Comment by bromagosa** [comment]
Sorry, Michael. We made a mess.

We merged `dev` into `master`, then removed the `dev` branch, and so all the PRs that were pointing to `dev` got (obviously) closed along with the branch :(

Can you please resubmit this PR to master?

**Comment by cycomachead** [comment]
Sure — why would we remove the dev branch? I thought we were going to keep it around?

We should really make dev the main branch on GitHub. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
Does this affect users?  I.e., are we uploading the merge to s.b.e?

**Comment by cycomachead** [comment]
Yes it does. And I’ll get to it today. 

We can do multiple uploads too. 

We need to have an email about releasing and plans I think. 

Sigh. There are too many problems with edX and I’ve been super swamped but I can get this fixed. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
So, if we're making 4.1 beta the thing users get from s.b.e/run, then we need to have an s.b.e/stable that gets 4.0, and we have to tell Piazza about it.

**Comment by cycomachead** [comment]
Sending email.

**Comment by cycomachead** [comment]
This is ready again @bromagosa @jmoenig

**Comment by bromagosa** [comment]
Hmm, there seem to be a few conflicts still. They look trivial to fix though :)

**Comment by cycomachead** [comment]
Sigh, my other PR was merged in. Haha. 

I’ll fix soon but we need this in 4.1. :)

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
Ok, ready again.

All the conflicts were from the same lines in fixing the file names. Makes me think we could use a bit of refactoring. :) ...for later!

**Comment by jmoenig** [comment]
Thanks a lot, Michael!

**Pull request merged**
