### PR TITLE
Update tools file

### PR DESCRIPTION
**Pull request by cycomachead**
This makes the following fixes.
* removes the duplicate `ask` and `tell` blocks
* adds `list → word %list` to be consistent since there's list/sentence blocks
and a `word → list` block but not a `list → word`, which has been confusing for a
while. :P

### CODE REVIEW

**Comment by jmoenig** [comment]
@brianharvey, the tools are your domain...

**Comment by jmoenig** [comment]
I'm still waiting for any feedback from @brianharvey about this...

**Comment by brianharvey** [comment]
Oops sorry for delay.  Crazy busy.

**Comment by jmoenig** [comment]
No problem, thanks for pulling this. I just placed it into http://snap.berkeley.edu/run

**Pull request merged**
