### PR TITLE
Update fr translations

### PR DESCRIPTION
**Pull request by damiencaselli**
This PR concerns translations for the French language.

It adds a couple of keys, fixes some existing ones, and formats file properly.

### CODE REVIEW

**Comment by jmoenig** [comment]
Thank you very much! I'll integrate this along with the next release (which might take up to a week or two this time).

**Comment by damiencaselli** [comment]
:+1:

**Comment by jmoenig** [comment]
Hi @damiencaselli and @show0k ! I'm about to pull this, but I'm not sure anymore: Does this PR need to be changed before I can pull it, or do you agree on the changes?

**Comment by jmoenig** [comment]
Actually, this all looks good to me from cursorily glancing over the changes. I'm pulling this now. Thanks!

**Comment by damiencaselli** [comment]
Sorry about the late answer, anyway I stick to my comment above, as mentioned by @jmoenig in the comments:

> Use the German translation file (named 'lang-de.js') as template for your
> own translations. Start with editing the original file, because that way
> you will be able to immediately check the results in your browsers while
> you're working on your translation (keep the local copy of snap.html open
> in your web browser, and refresh it as you progress with your
> translation).

(https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/lang-fr.js#L43-L48)

When (if) that changes, I'll gladly update the documentation.

**Comment by jmoenig** [comment]
Thanks! this. goes into the upcoming release now...

**Pull request merged**
