### PR TITLE
Delete those files with the special names.

### PR DESCRIPTION
**Pull request by an-OK-squirrel**
I couldn't find the blocks in the editor but this should still work.

### CODE REVIEW

**Comment by brianharvey** [comment]
The blocks in question are tools -- you get them with File>Import Tools.  And, it's not that I don't know how to delete files, I just don't want to do something like that without checking with Jens first.

**Comment by cycomachead** [comment]
@brianharvey These are the old versions of the tools blocks and are no longer needed in the repo, but should potentially still live on s.b.e. In reality though, I don't see many people clicking on help for those blocks in older projects.

**Comment by an-OK-squirrel** [comment]
Okay.

**Comment by jmoenig** [comment]
I *think* this has been taken care of by #944

**Comment by jmoenig** [comment]
Can this be closed? I think so...

**Comment by brianharvey** [comment]
Yes this has been fixed.

**Comment by jmoenig** [comment]
Thanks!

**Pull request closed without merging**
