### PR TITLE
Implement context functions

### PR DESCRIPTION
**Pull request by dekrain**
Implementation of #1469

### CODE REVIEW

**Comment by jmoenig** [comment]
I have no idea what this is about. Can we communicate a little bit more verbally? Like I'd love to know more about what it is you're doing, and not just guess from reading code. Otherwise I'm going to have to close all these cryptic contributions, because, frankly, I don't know what they are about.

**Comment by dekrain** [comment]
It implement a new type for expression for context. If it's function, it normally evaluates it as normal block.

**Comment by liam4** [comment]
I'm curious why you can't (or didn't) add `start` as an input right away?

```js
// Push a context. Stuff can be accessed using `proc`, `yield`
// can be used to cause Snap! to yield (e.g. wait-0-secs), and
// all arguments after those first two are inputs added to the
// procedure.
process.pushContext(function(proc, doYield, inptTime, inptStart) {
  if (!(Date.now() - start > time)) {
    doYield()
  }
})

process.context.addInput(1000)
process.context.addInput(Date.now())
```

Also, why would you really need `addInput` at all? Couldn't you do this?

```js
var time = 1000
var start = Date.now()

process.pushContext(function(proc, doYield) {
  if (!(Date.now() - start > time)) {
    doYield()
  }
})
```

This reminds me a bit of scratch-vm.. though I don't quite know how stuff like this works there, either :) -- just answers to those questions should help though, thanks.

Aside from those questions, I guess this is cool.

I don't quite understand the example in #1469, though..

**Comment by dekrain** [comment]
Don't inspect this, this is only example

**Comment by liam4** [comment]
Inspect? Like, look at how it works..?

Isn't that the point of an example?

**Comment by dekrain** [comment]
Ok, I mean: focus mostly on my feature. This is only example

**Comment by liam4** [comment]
But I don't know how your feature works or what it does, since you didn't describe it in the original post - so either the example should explain it, or you should explain it with words :)

(I'd go for well-commented examples explaining feature requests like this.)

**Comment by dekrain** [comment]
It will be fine if expression of context can be function

**Comment by brianharvey** [comment]
Wait, are you inventing continuations?  We already have those...

**Comment by dekrain** [comment]
No, I mean non-blocks expressions (functions)

**Comment by cycomachead** [comment]
This isn't something for Snap<em>!</em> _users_, right? 

In terms of #1469 that's something only people hacking on Snap<em>!</em> would do - so I don't think this belongs in Snap<em>!</em>.

**Comment by dekrain** [comment]
Nope. It's only for manually executing. (`Process.prototype.pushContext` etc.)

**Pull request closed without merging**
