### PR TITLE
Costumes tab name to Costumes/Backgrounds

### PR DESCRIPTION
**Pull request by jguille2**
A suggestion.

Adapt 'costumes' tab name to real name (Costumes for sprites and Backgrounds for stage).

Thanks,

Joan

### CODE REVIEW

**Comment by jmoenig** [comment]
Good point, thanks for the pull-request, @jguille2 !

**Comment by jguille2** [comment]
This second commit adapts "rename costume" to the context (costume for sprites, background for stage).

I would add these two new strings ('Backgrounds' and 'rename background') to translation files... but I think we need to arrange the translation system (actually not synchronized). I'll open another issue... and maybe I can help doing some work in this theme.

**Comment by jguille2** [comment]
This third commit (the last :) ) to adapt stage messages to turn pen trails into costumes/backgrounds.

Shorter strings messages would be better to reduce the number of translations but of course I've adapted to existing messages. In any case, two more strings to put into translations files.
We will talk about the translation system in #1551, and I'll update translations files with these 4 strings and with the rest of the pending work.

Thanks!!

**Comment by jmoenig** [comment]
Excellent, thanks @jguille2 !

**Pull request merged**
