### PR TITLE
index.html: preserve URL # on redirects

### PR DESCRIPTION
**Pull request by cycomachead**
Not sure how many people visit this page directly, but it can't hurt to do this.

### CODE REVIEW

**Comment by jmoenig** [comment]
You want me to pull this, right?

**Comment by cycomachead** [comment]
Yes, please. It's mostly a simple thing, but this allows snapsource/#<something> to work as-is.

**Comment by jmoenig** [comment]
Thanks! I'm finishing up a large-ish batch of new stuff to add, and plan/hope to work out a new release within the next days/week.

**Comment by cycomachead** [comment]
Sounds good! What's in there? :)

**Comment by jmoenig** [comment]
let's see:

* fixed weird input slot editing
* always export attached comments with script pics (also in the block editor)
* fixed %interaction hat block (made input static, i.e. non-droppable)
* adjust block editor's size to accomodate the whole custom block definition
* make block editor remember location and extent when acknowledging (for the session)
* speed up project loading by eliminating redundant redraws of blocks
* introduce a grab-threshold, so slight mouse micromovements will not prevent clicks anymore (by initiating drag-events), also (hopefully) fixes some other situations, such as the can't-click-on-dropdowns-in-Chrome-on-Windows issue
* expand list watchers inside result-bubbles to show as much of the whole list (first-level) as fist on the screen
* improve rendering of C-slots and "holes", avoid occasional horizontal line artifacts
* some more little things I've forgotten...

**Comment by cycomachead** [comment]
Awwwwwesome!! :+1:

**Pull request merged**
