### PR TITLE
Revert "Fix the MOTD feature."

### PR DESCRIPTION
**Pull request by jmoenig**
Reverts jmoenig/Snap--Build-Your-Own-Blocks#2020
doesn't work.

### CODE REVIEW

**Comment by cycomachead** [comment]
What doesn't work?

**Comment by jmoenig** [comment]
Ah, sorry for not responding. I was pulling this shortly before the release, and right when I tried it I got all kinds of errors in my JS console. In retrospect it occurs to me these errors might have been caused by the files it was looking for not being present in the "dev" distro or on my local server. So, yeah, this has probably nothing to do with your code, and all with the mechanism.

You know, I do regret this feature. I think just popping up an ```alert``` as we ended up doing last weekend might actually have been better, because it sure got everybody's attention. Maybe it's as easy as just that. The ```alert``` had the additional benefit of being right inside the ```snap.html``` file, so we didn't have to exchange more files in the mirrors.

One problem with the MOTD feature was aggressive browser caching. Since we're now addressing this by manually changing the version date in the ```snap.html``` file anyway, we might as well *only* touch that file when we need to alert users about impending doom.

Yes, I'm fine with taking the MOTD feature out altogether.

**Comment by brianharvey** [comment]
In that case, can we please leave the message code in snap.html, commented out, so we can revive it easily in a crisis?

**Comment by jmoenig** [comment]
inserting an ```alert('panic!')``` statement is easy enough, we don't need a template for that.

**Comment by brianharvey** [comment]
Easy for _you_.  Having a comment in the right place would make it easy for me also.

**Comment by cycomachead** [comment]
Thanks for mentioning that. It’s confusing when something doesn’t work even though I definitely tested that spect. 

Literally anywhere in JS that’s evaluates will suffice. 

But while alert is nice and effective, we should be careful. It’s one of those features that browser vendors are slowly restricting the use. In most browsers there’s now a checkbox that allows users to ignore alerts from a domain. I don’t know if it’s per-session or per-domain, but we need to be careful in the future. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment]
> One problem with the MOTD feature was aggressive browser caching. Since we're now addressing this by manually changing the version date in the snap.html file anyway, we might as well only touch that file when we need to alert users about impending doom.

Oh yeah, I missed this earlier. In the future if er need such a thing we can do `getURL('motd.txt?' + (new Date()).toString())` and that would fix any caching issues.

**Pull request merged**
