### PR TITLE
Translation fix

### PR DESCRIPTION
**Pull request by carloslfu**
Hi Jens. I am a native spanish speaker and I fixed this translation mistake.

### CODE REVIEW

**Comment by carloslfu** [comment]
I'm doing a best pull with more translation fixes

**Comment by jmoenig** [comment]
great! Oh, I *was* intending to pull this, are you going to re-open it?

**Comment by carloslfu** [comment]
I'm going to create a new PR because i removed the fork related to this PR.

**Comment by jmoenig** [comment]
Thanks!

**Pull request closed without merging**
