### PR TITLE
Fixed typo ('gobal' -> 'global')

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

**Comment by jmoenig** [comment]
OMG! How could this go unnoticed for so long? Thank you, Brian!

**Comment by cycomachead** [comment]
Well, at least it was consistent! ;)

**Comment by brollb** [comment]
no problem!

**Comment by jmoenig** [comment]
> Well, at least it was consistent! ;)

copy & paste is a grossly underappreciated best programming practice :-)

**Comment by bromagosa** [comment]
Haha! This happens to me all the time thanks to Vim autocompleting everything.

**Pull request merged**
