### PR TITLE
Make synchronous HTTP requests asynchronous

### LINKED ISSUE #1242: Project and libary loading should be async.
I know that jens doesn't like async things, but the current synchronous style makes the web browser display warnings that the tab has locked up and in some web browser like Firefox it locks up the entire browser for two or three minutes.

### PR DESCRIPTION
**Pull request by djdolphin**
Fixes #1242

### CODE REVIEW

**Comment by dekrain** [comment]
More in #1343

**Comment by cycomachead** [comment]
Aside from speed, this has no user-facing side effects, right?

**Comment by djdolphin** [comment]
I originally included this with the sound features pull request because for some reason, synchronous HTTP requests seem to mess with web audio in Firefox. Sending one synchronous HTTP request will suspend the audio context, and sending a second will resume it. (Yay, bugs!)

You can see this in the current version of Snap! if you play a long note, say 10 beats, and open the libraries, costumes, or sounds menu. The note will pause. Opening one of those menus again will resume the note.

**Comment by cycomachead** [comment]
Oh, yeah, that's a great point.

Sending sync requests block the rest of JS from executing on a page - which is why they're considered bad. 

Anyway, the LGTM, though I haven't had a chance to play around with it.

**Comment by djdolphin** [comment]
Hey, sorry for my absence. I've been pretty overwhelmed with school and stuff, but I've gotten a lot better at managing that lately. :)

I see that there have been changes to gui.js that seem to make this pull request irrelevant. Should I continue with the pull requests for the new sound features?

**Comment by cycomachead** [comment]
Did you handle async loading the `Examples` projects list? That's the one part that hasn't been done. 
Much of the changes to gui.js are due to the libraries and other media browsers, and BH's refactoring of URL anchors.

I don't know how easy merging will be, but it doesn't seem like it hurts to try - whatever isn't async loaded, should be. :)

**Comment by jmoenig** [comment]
Hi @djdolphin , thanks for keeping this alive! Yes, I did have to change some requests in gui.js to be asynchronous instead of synchronous. It would be great if you found others that still need switching over. If you do find such issues, please don't hesitate to issue a pull-request. Sounds is also a great feature that Snap needs, but I'm currently busy with other features, so I won't promise to pull it right away.

**Comment by djdolphin** [comment]
Ok, I'm going to close this and create a new, updated pull request to switch the rest over.

**Pull request closed without merging**
