### PR TITLE
Правка русского перевода

### PR DESCRIPTION
**Pull request by temaps**
Исправил ошибки и добавил недостающие переводы

### CODE REVIEW

**Comment by jmoenig** [comment]
Thank you!
This pull request not only updates the Russian translation but also addresses the issue that when you first open Snap the default names for Stage and Sprite are not localized. I've only noticed this issue myself after I've looked at the mechanism in your code that fixes this. Nice!
Before I pull this I'd like to find out why the default names are not already translated, because I'm pretty sure that at one point they used to, until something must have interfered. So, please hang on, while I investigate into this some more. I'll mark this as "blessed by Jens" anyway, so I don't forget to pull it for the next release. Again, thanks for the great work!

**Comment by jmoenig** [comment]
Hi, @temaps , I've fixed the issue of localizing "Stage" and "Sprite" on start up in this commit: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/commit/8a8d55c3e9bb84cd0374e95884f57a7f979ea43f . Again, thank you for pointing this issue out to me! The fix now supersedes your pull request inasmuch as the modifications to ```gui.js``` and ```objects.js``` are no longer needed. Please let me know if you would like me to pull your request anyway - in this case I would afterwards undo those changes again myself - or if you would prefer to adjust your pull-request accordingly. Thanks!

**Comment by temaps** [comment]
I do "git reset". Now only correction Russian localization :-)

**Comment by temaps** [comment]
In what folder to fold translated images from folder help?

**Comment by jmoenig** [comment]
Awesome, thanks for the edit!

Good question about translations for help panels. Currently this is not yet supported, but it clearly should be. We'll figure out something...

**Comment by temaps** [comment]
I merge pull request #1 from jmoenig/master.
When start new problem
snaptrans

**Comment by temaps** [comment]
My cure https://github.com/temaps/Snap-830/commit/01999fd6926a4cc07447f1ee491b5e9990b5b69c from https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1237 work correct...

**Comment by jmoenig** [comment]
Ooops, something obviously went awry with my fix. Thanks for notifying me of this! I'll revisit the issue.

**Comment by jmoenig** [comment]
I've just fixed the fix with 0c1ecf2b9a8f35e6745eabd304f9d7bdbde180f1 Can you please try again, whether it now works for you? Thanks!

**Comment by temaps** [comment]
Now OK :-)

**Comment by jmoenig** [comment]
Thank *you* for all the testing and feedback!

**Pull request merged**
